// Hand-written graded stories. Build with `npm run content`.
//
// Each sentence is [chinese, english]. Inside the Chinese:
//   |          forces a word break (the builder segments by longest dictionary match)
//   字{zì}     overrides the pinyin of the token just before it
//   words: { 词: [pinyin, gloss] }  names etc. the dictionary doesn't know

export default [
  {
    id: 'my-cat',
    level: 1,
    title: '我的猫',
    en: 'My cat',
    sentences: [
      ['我有一只{zhī}猫。', 'I have a cat.'],
      ['它很小，是白色的。', 'It is small and white.'],
      ['它每天都睡觉。', 'It sleeps every day.'],
      ['早上，它叫我起床。', 'In the morning, it wakes me up.'],
      ['我给它吃鱼，它很高兴。', 'I give it fish, and it is very happy.'],
      ['我也很高兴。', 'I am happy too.'],
    ],
  },
  {
    id: 'morning',
    level: 1,
    title: '早上',
    en: 'Morning',
    sentences: [
      ['今天早上七点，我起床了。', 'This morning I got up at seven.'],
      ['我喝了一杯水，吃了一个鸡蛋。', 'I drank a glass of water and ate an egg.'],
      ['外面天气很好。', 'The weather outside is nice.'],
      ['我走路去上班。', 'I walk to work.'],
      ['路上人很多，车也很多。', 'There are lots of people on the road, and lots of cars too.'],
      ['我到了公司，说：“大家早！”', 'I get to the office and say: “Morning, everyone!”'],
    ],
  },
  {
    id: 'moms-call',
    level: 1,
    title: '妈妈的电话',
    en: 'Mom’s call',
    sentences: [
      ['晚上，妈妈给我打电话。', 'In the evening, Mom calls me.'],
      ['她问我：“你吃饭了吗？”', 'She asks me: “Have you eaten?”'],
      ['我说：“吃了，你呢？”', 'I say: “I have. And you?”'],
      ['妈妈说她也吃了。', 'Mom says she has eaten too.'],
      ['她说：“天冷了，多穿衣服。”', 'She says: “It’s getting cold, wear more layers.”'],
      ['我说：“知道了，妈。”', 'I say: “I know, Mom.”'],
    ],
  },
  {
    id: 'rain',
    level: 1,
    title: '下雨了',
    en: 'It’s raining',
    sentences: [
      ['下午，天黑了。', 'In the afternoon, the sky went dark.'],
      ['下雨了，雨很大。', 'It started to rain, and it rained hard.'],
      ['我没有带伞。', 'I didn’t bring an umbrella.'],
      ['一个朋友来了，他有一把伞。', 'A friend came by, and he had an umbrella.'],
      ['我们一起走回家。', 'We walked home together.'],
      ['他说：“明天见！”', 'He said: “See you tomorrow!”'],
    ],
  },
  {
    id: 'groceries',
    level: 1,
    title: '去买菜',
    en: 'Grocery shopping',
    sentences: [
      ['星期六，我和妈妈去买菜。', 'On Saturday, Mom and I go grocery shopping.'],
      ['我们买了鱼、肉和青菜。', 'We buy fish, meat and greens.'],
      ['妈妈问：“这个多少钱？”', 'Mom asks: “How much is this?”'],
      ['老板说：“十块。”', 'The owner says: “Ten kuai.”'],
      ['妈妈说：“太贵了！”', 'Mom says: “That’s too expensive!”'],
      ['老板笑了：“好吧，八块。”', 'The owner laughs: “Fine, eight.”'],
    ],
  },
  {
    id: 'birthday',
    level: 1,
    title: '生日',
    en: 'Birthday',
    sentences: [
      ['今天是我的生日。', 'Today is my birthday.'],
      ['朋友们来我家。', 'My friends come to my place.'],
      ['他们给我一个大蛋糕。', 'They give me a big cake.'],
      ['蛋糕上写着“生日快乐”。', 'On the cake it says “Happy birthday”.'],
      ['我们一起唱歌，吃蛋糕。', 'We sing and eat cake together.'],
      ['这是很快乐的一天。', 'It is a very happy day.'],
    ],
  },
  {
    id: 'grandma-cooks',
    level: 2,
    title: '奶奶做饭',
    en: 'Grandma cooks',
    sentences: [
      ['我奶奶很会做饭。', 'My grandma is a great cook.'],
      ['每个星期天，我们都去奶奶家吃饭。', 'Every Sunday, we go to Grandma’s to eat.'],
      ['她做的红烧肉最好吃。', 'Her red-braised pork is the best.'],
      ['我问她：“奶奶，这个怎么做？”', 'I ask her: “Grandma, how do you make this?”'],
      ['奶奶笑着说：“很简单，就是要慢慢做。”', 'Grandma smiles: “It’s simple. You just have to cook it slowly.”'],
      ['她还教我怎么做汤。', 'She also teaches me how to make soup.'],
      ['吃完饭，我们一起看电视。', 'After dinner, we watch TV together.'],
      ['奶奶说：“下个星期再来！”', 'Grandma says: “Come again next week!”'],
    ],
  },
  {
    id: 'subway',
    level: 2,
    title: '坐地铁',
    en: 'On the subway',
    sentences: [
      ['我每天坐地铁上班。', 'I take the subway to work every day.'],
      ['早上八点的地铁，人特别多。', 'The 8 a.m. train is especially crowded.'],
      ['没有地方坐，我只好站着。', 'There’s nowhere to sit, so I have to stand.'],
      ['有的人在看手机，有的人在睡觉。', 'Some people are looking at their phones, some are sleeping.'],
      ['今天，一个老人上车了。', 'Today, an old man got on.'],
      ['一个年轻人马上站起来，让老人坐下。', 'A young man immediately stood up and let him sit down.'],
      ['老人说：“谢谢你！”', 'The old man said: “Thank you!”'],
      ['我觉得这个年轻人很好。', 'I thought that young man was really nice.'],
    ],
  },
  {
    id: 'restaurant',
    level: 2,
    title: '在饭店',
    en: 'At the restaurant',
    sentences: [
      ['晚上，我和朋友去一家新开的饭店。', 'In the evening, a friend and I go to a newly opened restaurant.'],
      ['服务员给我们菜单。', 'The waiter gives us the menu.'],
      ['菜单上有很多字，我不认识。', 'There are lots of characters on the menu I don’t recognize.'],
      ['朋友帮我一个一个地念。', 'My friend reads them out for me one by one.'],
      ['我们点了饺子、面条和一个鸡汤。', 'We order dumplings, noodles and a chicken soup.'],
      ['菜很快就来了。', 'The food comes quickly.'],
      ['饺子非常好吃，面条有点儿辣。', 'The dumplings are delicious, and the noodles are a bit spicy.'],
      ['吃完以后，朋友说：“今天我请客！”', 'When we finish, my friend says: “It’s on me today!”'],
    ],
  },
  {
    id: 'weekend',
    level: 2,
    title: '周末',
    en: 'The weekend',
    sentences: [
      ['这个周末天气很好。', 'The weather was lovely this weekend.'],
      ['星期六上午，我去公园跑步。', 'On Saturday morning, I went running in the park.'],
      ['公园里有很多人，有的在打球，有的在散步。', 'There were lots of people in the park, some playing ball, some out for a walk.'],
      ['下午，我在家看书。', 'In the afternoon, I read at home.'],
      ['星期天，我和家人一起去看电影。', 'On Sunday, I went to see a movie with my family.'],
      ['电影很有意思，我们都笑了。', 'The movie was fun, and we all laughed.'],
      ['晚上回家的时候，我觉得有点儿累，但是很开心。', 'Coming home that night, I felt a little tired, but happy.'],
    ],
  },
  {
    id: 'wechat',
    level: 2,
    title: '一条微信',
    en: 'A WeChat message',
    sentences: [
      ['今天我收到了姐姐的一条微信。', 'Today I got a WeChat message from my older sister.'],
      ['她说：“我下个月要来看你！”', 'She said: “I’m coming to see you next month!”'],
      ['我很高兴，因为我们已经一年没见面了。', 'I was thrilled, because we haven’t seen each other in a year.'],
      ['我回她：“太好了！你想吃什么？”', 'I replied: “Great! What do you want to eat?”'],
      ['姐姐说：“我想吃你做的饺子。”', 'She said: “I want the dumplings you make.”'],
      ['我说：“没问题，我现在就开始学！”', 'I said: “No problem, I’ll start learning right now!”'],
      ['她发了一个笑脸。', 'She sent a smiley face.'],
    ],
  },
  {
    id: 'keys',
    level: 2,
    title: '找钥匙',
    en: 'Looking for my keys',
    sentences: [
      ['早上我要出门的时候，找不到钥匙了。', 'This morning, just as I was about to leave, I couldn’t find my keys.'],
      ['我在桌子上找，没有。', 'I looked on the table. Not there.'],
      ['我在床下面找，也没有。', 'I looked under the bed. Not there either.'],
      ['我开始着急了，因为上班要晚了。', 'I started to panic, because I was going to be late for work.'],
      ['这时候，我看见猫在沙发上玩一个东西。', 'Just then, I saw the cat playing with something on the sofa.'],
      ['我走过去一看，是我的钥匙！', 'I walked over to look. It was my keys!'],
      ['我笑着说：“原来是你！”', 'I laughed: “So it was you!”'],
    ],
  },
  {
    id: 'new-year',
    level: 3,
    title: '过年',
    en: 'Chinese New Year',
    sentences: [
      ['过年是中国人最重要的节日。', 'New Year is the most important holiday for Chinese people.'],
      ['每年过年，我们全家人都会回到爷爷奶奶家。', 'Every New Year, the whole family goes back to my grandparents’ home.'],
      ['大家一起包饺子，一边包一边聊天。', 'Everyone makes dumplings together, chatting as they fold.'],
      ['孩子们最喜欢收红包。', 'The kids love getting red envelopes most of all.'],
      ['晚上十二点，外面放起了烟花，天空一下子变得很亮。', 'At midnight, fireworks go off outside and the sky suddenly lights up.'],
      ['爷爷说：“新的一年，希望大家身体健康，万事如意。”', 'Grandpa says: “In the new year, I wish everyone good health and that all goes well.”'],
      ['我们一起说：“新年快乐！”', 'Together we say: “Happy New Year!”'],
      ['我觉得过年最好的地方，不是吃的，也不是红包，而是一家人在一起。', 'For me, the best part of New Year isn’t the food or the red envelopes. It’s the family being together.'],
    ],
  },
  {
    id: 'shanghai',
    level: 3,
    title: '回上海',
    en: 'Back to Shanghai',
    sentences: [
      ['去年夏天，我跟爸爸回了一次上海。', 'Last summer, I went back to Shanghai with my dad.'],
      ['爸爸是在上海长大的。', 'Dad grew up in Shanghai.'],
      ['他带我去看他小时候住的地方。', 'He took me to see where he lived as a kid.'],
      ['那条小路还在，但是旁边多了很多高楼。', 'The little lane was still there, but there were lots of tall buildings next to it now.'],
      ['路边有一个老人在卖早饭，爸爸一下子就认出了他。', 'An old man was selling breakfast by the road, and Dad recognized him right away.'],
      ['他们用上海话聊了很久，我只听懂了一点儿。', 'They chatted in Shanghainese for a long time. I only understood a little.'],
      ['爸爸买了两个生煎包，说：“这是我小时候最喜欢吃的。”', 'Dad bought two pan-fried buns and said: “These were my favorite as a kid.”'],
      ['我吃了一口，真的很好吃。', 'I took a bite. They really were delicious.'],
      ['那天晚上，爸爸跟我说了很多以前的事。', 'That night, Dad told me a lot about the old days.'],
      ['我觉得我更了解他了。', 'I felt I understood him better.'],
    ],
  },
  {
    id: 'learning-to-read',
    level: 3,
    title: '学认字',
    en: 'Learning to read',
    sentences: [
      ['我从小就会说中文，但是认识的字不多。', 'I’ve spoken Chinese since I was little, but I don’t know many characters.'],
      ['每次看到中文菜单，我都要问别人。', 'Every time I see a Chinese menu, I have to ask someone.'],
      ['今年我决定开始学认字。', 'This year I decided to start learning to read.'],
      ['我每天学几个新词，还读一个小故事。', 'Every day I learn a few new words and read a short story.'],
      ['一开始很难，很多字看起来都差不多。', 'At first it was hard. Lots of characters looked almost the same.'],
      ['可是慢慢地，我认识的字越来越多了。', 'But slowly, I recognized more and more of them.'],
      ['上个星期，我给奶奶发了一条中文微信。', 'Last week, I sent Grandma a WeChat message in Chinese.'],
      ['奶奶很快就回了我：“你的中文进步了！”', 'She replied right away: “Your Chinese has improved!”'],
      ['我看得懂她的回复，心里特别高兴。', 'I could read her reply, and I was so happy.'],
    ],
  },
  {
    id: 'grandpa',
    level: 3,
    title: '爷爷的故事',
    en: 'Grandpa’s story',
    sentences: [
      ['爷爷年轻的时候，是一个老师。', 'When Grandpa was young, he was a teacher.'],
      ['他在一个很小的学校工作，学校里只有二十几个学生。', 'He worked at a tiny school with only twenty-some students.'],
      ['那时候，学生们很穷，很多人没有书。', 'Back then the students were poor, and many had no books.'],
      ['爷爷就自己写书，一个字一个字地写在纸上。', 'So Grandpa wrote books himself, character by character on paper.'],
      ['晚上，他常常工作到很晚。', 'He often worked late into the night.'],
      ['后来，他的很多学生都上了大学。', 'Later, many of his students went on to university.'],
      ['现在，还有学生每年过年来看他。', 'Even now, some students visit him every New Year.'],
      ['爷爷说：“当老师，是我这一辈子最快乐的事。”', 'Grandpa says: “Being a teacher was the happiest thing in my life.”'],
    ],
  },
  {
    id: 'lost-dog',
    level: 3,
    title: '小狗走丢了',
    en: 'The lost puppy',
    words: { 豆豆: ['dòu dòu', 'Doudou (the puppy’s name)'] },
    sentences: [
      ['邻居家的小狗叫豆豆，它很可爱，也很聪明。', 'The neighbors’ puppy is called Doudou. It’s cute and very clever.'],
      ['有一天下午，豆豆不见了。', 'One afternoon, Doudou disappeared.'],
      ['邻居非常着急，到处找它。', 'The neighbors were frantic and looked everywhere.'],
      ['我也出来帮忙，我们一边走一边叫：“豆豆！豆豆！”', 'I came out to help, and we walked around calling: “Doudou! Doudou!”'],
      ['找了两个小时，还是没有找到。', 'After two hours, we still hadn’t found it.'],
      ['天快黑的时候，一个小学生说，他在公园里看见了一只{zhī}小|白狗。', 'Just before dark, a schoolkid said he’d seen a little white dog in the park.'],
      ['我们马上跑到公园。', 'We ran straight to the park.'],
      ['豆豆正在树下面，和几个孩子一起玩呢！', 'Doudou was under a tree, playing with some kids!'],
      ['邻居抱起豆豆，又高兴又生气地说：“你跑到哪儿去了？”', 'The neighbor scooped Doudou up, happy and cross at once: “Where did you run off to?”'],
    ],
  },
  {
    id: 'dumplings',
    level: 3,
    title: '第一次包饺子',
    en: 'My first dumplings',
    sentences: [
      ['上个周末，我第一次自己包饺子。', 'Last weekend, I made dumplings on my own for the first time.'],
      ['我先去超市买了面粉、肉和白菜。', 'First I went to the supermarket for flour, meat and napa cabbage.'],
      ['回家以后，我给妈妈打视频电话，请她教我。', 'Back home, I video-called Mom and asked her to teach me.'],
      ['妈妈说：“肉和菜要切{qiē}得很小，再放一点儿盐和油。”', 'Mom said: “Chop the meat and vegetables very fine, then add a little salt and oil.”'],
      ['包饺子比我想的难多了。', 'Making dumplings was much harder than I thought.'],
      ['我包的饺子有的太大，有的太小，还有的一煮就破了。', 'Some of mine were too big, some too small, and some burst as soon as they boiled.'],
      ['妈妈在视频里看着我，笑得不行。', 'Watching me on video, Mom couldn’t stop laughing.'],
      ['最后，我还是吃到了自己包的饺子。', 'In the end, I still got to eat dumplings I made myself.'],
      ['虽然不太好看，但是我觉得特别好吃。', 'They weren’t pretty, but I thought they were delicious.'],
    ],
  },
  {
    id: 'letter',
    level: 4,
    title: '给奶奶的信',
    en: 'A letter to Grandma',
    sentences: [
      ['奶奶：您好！好久没有给您写信了。', 'Dear Grandma, it’s been so long since I wrote to you.'],
      ['我在这边一切都好，工作虽然有点儿忙，但是很有意思。', 'Everything is fine here. Work is a little busy, but interesting.'],
      ['最近我在学中文，每天都读一点儿。', 'Lately I’ve been studying Chinese and reading a little every day.'],
      ['以前我只会说，不会读，现在我已经认识很多字了。', 'I used to only speak it, not read it. Now I know a lot of characters.'],
      ['我还记得小时候，您常常给我讲故事。', 'I still remember how you used to tell me stories when I was little.'],
      ['那时候我听得很认真，可是书上的字，一个也不认识。', 'I listened so carefully, but I couldn’t read a single character in the book.'],
      ['现在我终于可以自己读故事了。', 'Now I can finally read stories on my own.'],
      ['等我回家的时候，我想给您读一个。', 'When I come home, I want to read one to you.'],
      ['请您一定要注意身体。祝您身体健康！', 'Please take good care of yourself. Wishing you good health!'],
    ],
  },
  {
    id: 'old-street',
    level: 4,
    title: '老街',
    en: 'The old street',
    sentences: [
      ['我家附近有一条老街，已经有一百多年了。', 'Near my home there’s an old street that’s over a hundred years old.'],
      ['街两边都是小店，有卖茶的，有卖包子的，还有修自行车的。', 'Both sides are lined with little shops: tea sellers, bun sellers, even a bike repairman.'],
      ['每天早上，老街上最热闹。', 'Mornings are when the old street is busiest.'],
      ['卖包子的阿姨认识每一个客人，她总是笑着问：“今天要几个？”', 'The bun lady knows every customer and always asks with a smile: “How many today?”'],
      ['修自行车的老王已经七十多岁了，可是他的手还是很快。', 'Old Wang, who fixes bikes, is over seventy, but his hands are still quick.'],
      ['去年，有人说要把老街拆了，盖新的大楼。', 'Last year, someone said they’d tear the street down and put up new towers.'],
      ['很多人都不|同意，大家都说，老街是我们的记忆。', 'Lots of people objected. Everyone said the old street is our memory.'],
      ['后来，老街留下来了。', 'In the end, the old street stayed.'],
      ['现在，每次走过老街，我都会停下来买一杯茶，和老王聊几句。', 'Now, whenever I walk down it, I stop for a cup of tea and a few words with Old Wang.'],
      ['我希望这条街可以一直在这里。', 'I hope this street will always be here.'],
    ],
  },
];
